export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const TOGGLE_CHEM_MODAL = "TOGGLE_CHEM_MODAL";
export const TOGGLE_BIO_MODAL = "TOGGLE_BIO_MODAL";

export const LOG_OUT = "LOG_OUT";

export const CHANGE_TEST_STATUS_REQUEST = "CHANGE_TEST_STATUS_REQUEST";
export const CHANGE_TEST_STATUS_SUCCESS = "CHANGE_TEST_STATUS_SUCCESS";
export const CHANGE_TEST_STATUS_FAILURE = "CHANGE_TEST_STATUS_FAILURE";

export const CHANGE_MESSAGE = "CHANGE_MESSAGE";

export const FINISHED_TEST_REQUEST = "FINISHED_TEST_REQUEST";
export const FINISHED_TEST_SUCCESS = "FINISHED_TEST_SUCCESS";
export const FINISHED_TEST_FAILURE = "FINISHED_TEST_FAILURE";

export const GET_CLASS_INFO_REQUEST = "GET_CLASS_INFO_REQUEST";
export const GET_CLASS_INFO_SUCCESS = "GET_CLASS_INFO_SUCCESS";
export const GET_CLASS_INFO_FAILURE = "GET_CLASS_INFO_FAILURE";

export const GET_RAZDEL_INFO_REQUEST = "GET_RAZDEL_INFO_REQUEST";
export const GET_RAZDEL_INFO_SUCCESS = "GET_RAZDEL_INFO_SUCCESS";
export const GET_RAZDEL_INFO_FAILURE = "GET_RAZDEL_INFO_FAILURE";

export const ADD_RAZDEL_REQUEST = "ADD_RAZDEL_REQUEST";
export const ADD_RAZDEL_SUCCESS = "ADD_RAZDEL_SUCCESS";
export const ADD_RAZDEL_FAILURE = "ADD_RAZDEL_FAILURE";

export const DELETE_RAZDEL_REQUEST = "DELETE_RAZDEL_REQUEST";
export const DELETE_RAZDEL_SUCCESS = "DELETE_RAZDEL_SUCCESS";
export const DELETE_RAZDEL_FAILURE = "DELETE_RAZDEL_FAILURE";

export const GET_TEST_REQUEST = "GET_TEST_REQUEST";
export const GET_TEST_SUCCESS = "GET_TEST_SUCCESS";
export const GET_TEST_FAILURE = "GET_TEST_FAILURE";

export const ADD_TEST_REQUEST = "ADD_TEST_REQUEST";
export const ADD_TEST_SUCCESS = "ADD_TEST_SUCCESS";
export const ADD_TEST_FAILURE = "ADD_TEST_FAILURE";

export const DELETE_TEST_REQUEST = "DELETE_TEST_REQUEST";
export const DELETE_TEST_SUCCESS = "DELETE_TEST_SUCCESS";
export const DELETE_TEST_FAILURE = "DELETE_TEST_FAILURE";

export const GET_QUESTION_REQUEST = "GET_QUESTION_REQUEST";
export const GET_QUESTION_SUCCESS = "GET_QUESTION_SUCCESS";
export const GET_QUESTION_FAILURE = "GET_QUESTION_FAILURE";

export const ADD_QUESTION_REQUEST = "ADD_QUESTION_REQUEST";
export const ADD_QUESTION_SUCCESS = "ADD_QUESTION_SUCCESS";
export const ADD_QUESTION_FAILURE = "ADD_QUESTION_FAILURE";

export const DELETE_QUESTION_REQUEST = "DELETE_QUESTION_REQUEST";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const DELETE_QUESTION_FAILURE = "DELETE_QUESTION_FAILURE";
