export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const TOGGLE_CHEM_MODAL = "TOGGLE_CHEM_MODAL";
export const TOGGLE_BIO_MODAL = "TOGGLE_BIO_MODAL";

export const LOG_OUT = "LOG_OUT";

export const CHANGE_TEST_STATUS_REQUEST = "CHANGE_TEST_STATUS_REQUEST";
export const CHANGE_TEST_STATUS_SUCCESS = "CHANGE_TEST_STATUS_SUCCESS";
export const CHANGE_TEST_STATUS_FAILURE = "CHANGE_TEST_STATUS_FAILURE";

export const CHANGE_MESSAGE = "CHANGE_MESSAGE";

export const FINISHED_TEST_REQUEST = "FINISHED_TEST_REQUEST";
export const FINISHED_TEST_SUCCESS = "FINISHED_TEST_SUCCESS";
export const FINISHED_TEST_FAILURE = "FINISHED_TEST_FAILURE";

export const GET_CLASS_INFO_REQUEST = "GET_CLASS_INFO_REQUEST";
export const GET_CLASS_INFO_SUCCESS = "GET_CLASS_INFO_SUCCESS";
export const GET_CLASS_INFO_FAILURE = "GET_CLASS_INFO_FAILURE";
